language: python
services:
  - postgresql
before_script:
  - psql -c 'create database test_db;' -U postgres
python:
  - "3.5"
install: "pip install -r requirements.txt"
notifications: 
  slack:
    on_success: change
    on_failure: change
script: pytest
