# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-04 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('feeds_id', models.AutoField(primary_key=True, serialize=False)),
                ('feeds', models.CharField(max_length=200)),
                ('time_posted', models.TimeField()),
                ('user_feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Registration')),
            ],
        ),
    ]
