# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-08 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-created', '-time_updated']},
        ),
    ]
