# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-16 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_feed_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feed',
            options={'ordering': ['-timestamp', '-time_updated']},
        ),
    ]
