# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-04 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=300)),
                ('time_posted', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('friends_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Registration')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('notifications', models.CharField(max_length=20)),
            ],
        ),
    ]
