# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-10 21:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trial_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feeds',
        ),
        migrations.DeleteModel(
            name='Friends',
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
