# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-11 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trial_app', '0003_auto_20170111_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=300)),
                ('time_posted', models.TimeField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Feeds',
            new_name='Feed',
        ),
        migrations.RenameModel(
            old_name='Friends',
            new_name='Friend',
        ),
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
        migrations.RenameModel(
            old_name='Notifications',
            new_name='Notification',
        ),
        migrations.AlterField(
            model_name='posts',
            name='comment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Trial_app.Comment'),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
