# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-05 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='app_user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.Registration'),
        ),
    ]
