# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-05 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessages',
            fields=[
                ('user_messages_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_messages', models.CharField(max_length=500)),
                ('user_messages_time', models.TimeField()),
                ('app_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Registration')),
            ],
        ),
    ]
