# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-28 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessages',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
