# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-08 16:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermessages',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='usermessages',
            old_name='user_messages_timestamp',
            new_name='created',
        ),
        migrations.AddField(
            model_name='usermessages',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usermessages',
            name='user_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_from_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usermessages',
            name='user_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_to_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
