# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-05 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessages',
            name='conversations',
        ),
    ]
