# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-08 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0002_auto_20170808_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermessages',
            old_name='user_messages_id',
            new_name='messages_id',
        ),
    ]
